# Generated by Django 3.2.3 on 2021-06-05 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_customfieldanswer'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_answer', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custum_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customfield')),
                ('lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.lead')),
            ],
        ),
    ]
