# Generated by Django 3.2.3 on 2021-06-09 14:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_customfieldanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_api_key',
            field=models.CharField(default=uuid.UUID('e9e8ade2-2f32-4cf9-9a74-2cd48cd5c284'), max_length=50, unique=True),
        ),
    ]
