# Generated by Django 3.2.3 on 2021-06-04 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customfield_customfieldchoise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('email', 'Email'), ('drop_down', 'Drop Down'), ('radio', 'Radio'), ('date', 'Date'), ('time', 'Time')], default='Text', max_length=50),
        ),
        migrations.CreateModel(
            name='CustomFieldAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_answer', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custum_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customfield')),
            ],
        ),
    ]
