# Generated by Django 3.2.3 on 2021-06-05 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_auto_20210604_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadstage',
            name='leads_reorder_logic',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='GmailCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200, null=True)),
                ('refresh_token', models.CharField(max_length=200, null=True)),
                ('id_token', models.CharField(max_length=200, null=True)),
                ('token_uri', models.CharField(max_length=200, null=True)),
                ('scopes', models.CharField(max_length=1000, null=True)),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('valid', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
