# Generated by Django 3.2.3 on 2021-06-05 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210605_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stageindexorder',
            name='company',
        ),
        migrations.DeleteModel(
            name='StageElementIndexLogic',
        ),
        migrations.DeleteModel(
            name='StageIndexOrder',
        ),
    ]
