# Generated by Django 3.2.3 on 2021-06-05 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210605_2147'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomFieldAnswer',
        ),
    ]
