# Generated by Django 3.2.3 on 2021-06-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_customfieldanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailcredential',
            name='client_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gmailcredential',
            name='client_secret',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
